## Example of embedding

In [10]:
from tensorflow.keras.preprocessing.text import one_hot

In [11]:
## Sentences

sent = [  'the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good'
]

In [12]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [13]:
## Define the vocabulary size
voc_size = 10000

In [14]:
## one Hot Representation
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[1090, 4997, 118, 2124],
 [1090, 4997, 118, 8907],
 [1090, 1099, 118, 3303],
 [5761, 508, 7458, 3873],
 [5761, 508, 7458, 6866, 9695],
 [145, 1090, 4205, 118, 1369],
 [1913, 1431, 1293, 6866]]

In [18]:
## Word Embedding Representaion

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [ ]:
## Setting sentence length for easy RNN training (Pre-padding)

sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1090 4997  118 2124]
 [   0    0    0    0 1090 4997  118 8907]
 [   0    0    0    0 1090 1099  118 3303]
 [   0    0    0    0 5761  508 7458 3873]
 [   0    0    0 5761  508 7458 6866 9695]
 [   0    0    0  145 1090 4205  118 1369]
 [   0    0    0    0 1913 1431 1293 6866]]


In [20]:
## Feature Representation 
dim = 10

In [22]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

In [23]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [24]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 328ms/step


array([[[ 4.18034457e-02,  1.94349326e-02, -4.70024459e-02,
         -1.00771412e-02, -1.44489519e-02,  1.82314254e-02,
         -7.34034926e-03, -9.02775675e-03,  1.58763193e-02,
         -4.93177660e-02],
        [ 4.18034457e-02,  1.94349326e-02, -4.70024459e-02,
         -1.00771412e-02, -1.44489519e-02,  1.82314254e-02,
         -7.34034926e-03, -9.02775675e-03,  1.58763193e-02,
         -4.93177660e-02],
        [ 4.18034457e-02,  1.94349326e-02, -4.70024459e-02,
         -1.00771412e-02, -1.44489519e-02,  1.82314254e-02,
         -7.34034926e-03, -9.02775675e-03,  1.58763193e-02,
         -4.93177660e-02],
        [ 4.18034457e-02,  1.94349326e-02, -4.70024459e-02,
         -1.00771412e-02, -1.44489519e-02,  1.82314254e-02,
         -7.34034926e-03, -9.02775675e-03,  1.58763193e-02,
         -4.93177660e-02],
        [-2.42005121e-02,  4.91190217e-02, -3.31241377e-02,
          1.45515315e-02, -1.00170858e-02, -2.19312068e-02,
          1.10568888e-02, -4.30265181e-02,  1.178079